# Generated by Django 4.1.3 on 2023-01-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_department_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='size',
            field=models.IntegerField(default=2),
        ),
    ]
