# Generated by Django 4.1.3 on 2023-01-13 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_remove_userinfo_data_remove_userinfo_size_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
