# Generated by Django 4.1.3 on 2023-04-24 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='attitude_recommend',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='心态建议id')),
                ('attitude', models.SmallIntegerField(choices=[(0, '高兴'), (1, '搞笑'), (2, '期待'), (3, '肯定'), (4, '感动'), (5, '悲伤'), (6, '愤怒'), (7, '厌恶'), (8, '担心'), (9, '无聊'), (10, '警惕'), (11, '惊讶'), (12, '无所谓')], verbose_name='心态')),
                ('suggestion', models.CharField(max_length=1024, verbose_name='建议')),
            ],
        ),
        migrations.CreateModel(
            name='comments_statistics',
            fields=[
                ('comments_id', models.AutoField(primary_key=True, serialize=False, verbose_name='心态统计id')),
                ('comment_time', models.DateTimeField(verbose_name='心态时间')),
                ('content', models.CharField(max_length=255, verbose_name='内容')),
                ('province', models.SmallIntegerField(choices=[(0, '北京'), (1, '天津'), (2, '上海'), (3, '重庆'), (4, '河北'), (5, '山西'), (6, '辽宁'), (7, '吉林'), (8, '黑龙江'), (9, '江苏'), (10, '浙江'), (11, '安徽'), (12, '福建'), (13, '江西'), (14, '山东'), (15, '河南'), (16, '湖北'), (17, '湖南'), (18, '广东'), (19, '海南'), (20, '四川'), (21, '贵州'), (22, '云南'), (23, '陕西'), (24, '甘肃'), (25, '青海'), (26, '台湾'), (27, '内蒙古'), (28, '广西'), (29, '西藏'), (30, '宁夏'), (31, '新疆'), (32, '香港'), (33, '澳门'), (34, '其他')], verbose_name='省份')),
                ('attitude', models.SmallIntegerField(choices=[(0, '高兴'), (1, '搞笑'), (2, '期待'), (3, '肯定'), (4, '感动'), (5, '悲伤'), (6, '愤怒'), (7, '厌恶'), (8, '担心'), (9, '无聊'), (10, '警惕'), (11, '惊讶'), (12, '无所谓')], verbose_name='心态')),
                ('thumbs', models.IntegerField(verbose_name='点赞数')),
            ],
        ),
        migrations.CreateModel(
            name='crawler_information',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='爬虫信息id')),
                ('time', models.DateTimeField(verbose_name='爬虫时间')),
                ('add', models.IntegerField(verbose_name='新增爬虫数量')),
                ('positive', models.IntegerField(verbose_name='积极')),
                ('neutral', models.IntegerField(verbose_name='中性')),
                ('negative', models.IntegerField(verbose_name='消极')),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False, verbose_name='事件id')),
                ('event', models.CharField(max_length=255, verbose_name='事件')),
                ('post', models.CharField(max_length=512, verbose_name='内容')),
                ('time', models.DateTimeField(verbose_name='事件时间')),
                ('province', models.SmallIntegerField(choices=[(0, '北京'), (1, '天津'), (2, '上海'), (3, '重庆'), (4, '河北'), (5, '山西'), (6, '辽宁'), (7, '吉林'), (8, '黑龙江'), (9, '江苏'), (10, '浙江'), (11, '安徽'), (12, '福建'), (13, '江西'), (14, '山东'), (15, '河南'), (16, '湖北'), (17, '湖南'), (18, '广东'), (19, '海南'), (20, '四川'), (21, '贵州'), (22, '云南'), (23, '陕西'), (24, '甘肃'), (25, '青海'), (26, '台湾'), (27, '内蒙古'), (28, '广西'), (29, '西藏'), (30, '宁夏'), (31, '新疆'), (32, '香港'), (33, '澳门'), (34, '其他')], verbose_name='省份')),
                ('thumbs', models.IntegerField(verbose_name='点赞数')),
            ],
        ),
        migrations.CreateModel(
            name='event_key_words',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='关键词id')),
                ('time', models.DateTimeField(verbose_name='事件时间')),
                ('word', models.CharField(max_length=32, verbose_name='关键词')),
                ('numbers', models.IntegerField(verbose_name='重复次数')),
            ],
        ),
        migrations.CreateModel(
            name='event_statistics',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False, verbose_name='事件统计id')),
                ('post', models.CharField(max_length=512, verbose_name='内容')),
                ('summary', models.CharField(max_length=255, verbose_name='总结')),
                ('time', models.CharField(blank=True, max_length=32, verbose_name='时间')),
                ('place', models.CharField(blank=True, max_length=32, verbose_name='地点')),
                ('trigger', models.CharField(blank=True, max_length=32, verbose_name='触发器')),
                ('people', models.CharField(blank=True, max_length=32, verbose_name='人物')),
                ('things', models.CharField(blank=True, max_length=32, verbose_name='事情')),
                ('moves', models.CharField(blank=True, max_length=32, verbose_name='动作')),
                ('events', models.CharField(blank=True, max_length=32, verbose_name='事件')),
                ('institution', models.CharField(blank=True, max_length=32, verbose_name='机构')),
                ('numbers', models.CharField(blank=True, max_length=32, verbose_name='数量')),
                ('unit', models.CharField(blank=True, max_length=32, verbose_name='单元')),
                ('reason', models.CharField(blank=True, max_length=32, verbose_name='原因')),
                ('total_attitudes', models.SmallIntegerField(choices=[(0, '高兴'), (1, '搞笑'), (2, '期待'), (3, '肯定'), (4, '感动'), (5, '悲伤'), (6, '愤怒'), (7, '厌恶'), (8, '担心'), (9, '无聊'), (10, '警惕'), (11, '惊讶'), (12, '无所谓')], verbose_name='心态')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户反馈id')),
                ('score', models.FloatField(verbose_name='评分')),
                ('type', models.SmallIntegerField(choices=[(0, '命名体识别'), (1, '情感分类'), (2, '文本摘要'), (3, '引导建议生成')], verbose_name='评价模型')),
                ('input', models.CharField(max_length=512, verbose_name='输入')),
                ('output', models.CharField(max_length=512, verbose_name='输出')),
            ],
        ),
        migrations.CreateModel(
            name='untrain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='待校正id')),
                ('label', models.SmallIntegerField(choices=[(0, '高兴'), (1, '搞笑'), (2, '期待'), (3, '肯定'), (4, '感动'), (5, '悲伤'), (6, '愤怒'), (7, '厌恶'), (8, '担心'), (9, '无聊'), (10, '警惕'), (11, '惊讶'), (12, '无所谓')], verbose_name='心态标签')),
                ('comments_id', models.ForeignKey(db_column='comments_id', on_delete=django.db.models.deletion.CASCADE, to='app.comments_statistics')),
            ],
        ),
        migrations.CreateModel(
            name='train',
            fields=[
                ('train_id', models.AutoField(primary_key=True, serialize=False, verbose_name='训练id')),
                ('label', models.SmallIntegerField(choices=[(0, '高兴'), (1, '搞笑'), (2, '期待'), (3, '肯定'), (4, '感动'), (5, '悲伤'), (6, '愤怒'), (7, '厌恶'), (8, '担心'), (9, '无聊'), (10, '警惕'), (11, '惊讶'), (12, '无所谓')], verbose_name='心态标签')),
                ('correct', models.BooleanField(verbose_name='更正标签')),
                ('time', models.DateTimeField(verbose_name='手动更正时间')),
                ('comments_id', models.ForeignKey(db_column='comments_id', on_delete=django.db.models.deletion.CASCADE, to='app.comments_statistics')),
            ],
        ),
        migrations.CreateModel(
            name='event_distribution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='事件信息id')),
                ('event_time', models.DateTimeField(verbose_name='事件时间')),
                ('province', models.SmallIntegerField(choices=[(0, '北京'), (1, '天津'), (2, '上海'), (3, '重庆'), (4, '河北'), (5, '山西'), (6, '辽宁'), (7, '吉林'), (8, '黑龙江'), (9, '江苏'), (10, '浙江'), (11, '安徽'), (12, '福建'), (13, '江西'), (14, '山东'), (15, '河南'), (16, '湖北'), (17, '湖南'), (18, '广东'), (19, '海南'), (20, '四川'), (21, '贵州'), (22, '云南'), (23, '陕西'), (24, '甘肃'), (25, '青海'), (26, '台湾'), (27, '内蒙古'), (28, '广西'), (29, '西藏'), (30, '宁夏'), (31, '新疆'), (32, '香港'), (33, '澳门'), (34, '其他')], verbose_name='省份')),
                ('hot', models.IntegerField(verbose_name='热度')),
                ('event_id', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, to='app.event_statistics')),
            ],
        ),
        migrations.AddField(
            model_name='comments_statistics',
            name='event_id',
            field=models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, to='app.event_statistics'),
        ),
        migrations.CreateModel(
            name='comments_key_words',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='关键词id')),
                ('time', models.DateTimeField(verbose_name='事件时间')),
                ('word', models.CharField(max_length=32, verbose_name='关键词')),
                ('numbers', models.IntegerField(verbose_name='重复次数')),
                ('attitude', models.SmallIntegerField(choices=[(0, '高兴'), (1, '搞笑'), (2, '期待'), (3, '肯定'), (4, '感动'), (5, '悲伤'), (6, '愤怒'), (7, '厌恶'), (8, '担心'), (9, '无聊'), (10, '警惕'), (11, '惊讶'), (12, '无所谓')], verbose_name='心态')),
                ('event_id', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, to='app.event_statistics')),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('comments_id', models.AutoField(primary_key=True, serialize=False, verbose_name='评论id')),
                ('content', models.CharField(max_length=255, verbose_name='内容')),
                ('time', models.DateTimeField(verbose_name='评论时间')),
                ('province', models.SmallIntegerField(choices=[(0, '北京'), (1, '天津'), (2, '上海'), (3, '重庆'), (4, '河北'), (5, '山西'), (6, '辽宁'), (7, '吉林'), (8, '黑龙江'), (9, '江苏'), (10, '浙江'), (11, '安徽'), (12, '福建'), (13, '江西'), (14, '山东'), (15, '河南'), (16, '湖北'), (17, '湖南'), (18, '广东'), (19, '海南'), (20, '四川'), (21, '贵州'), (22, '云南'), (23, '陕西'), (24, '甘肃'), (25, '青海'), (26, '台湾'), (27, '内蒙古'), (28, '广西'), (29, '西藏'), (30, '宁夏'), (31, '新疆'), (32, '香港'), (33, '澳门'), (34, '其他')], verbose_name='省份')),
                ('thumbs', models.IntegerField(verbose_name='点赞数')),
                ('attitude', models.SmallIntegerField(choices=[(0, '高兴'), (1, '搞笑'), (2, '期待'), (3, '肯定'), (4, '感动'), (5, '悲伤'), (6, '愤怒'), (7, '厌恶'), (8, '担心'), (9, '无聊'), (10, '警惕'), (11, '惊讶'), (12, '无所谓')], verbose_name='心态')),
                ('event_id', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, to='app.event')),
            ],
        ),
    ]
