# Generated by Django 4.1.3 on 2023-02-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_statistics',
            name='hot',
            field=models.IntegerField(verbose_name='热度'),
        ),
    ]
