# Generated by Django 4.1.3 on 2023-03-02 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_attitude_statistics_attitude_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='attitude_statistics',
        ),
    ]
