# Generated by Django 4.1.3 on 2023-03-04 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_attitude_statistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='key_words',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='关键词id')),
                ('time', models.DateTimeField(verbose_name='事件时间')),
                ('word', models.CharField(max_length=32, verbose_name='关键词')),
                ('numbers', models.IntegerField(max_length=64, verbose_name='重复次数')),
            ],
        ),
        migrations.CreateModel(
            name='event_information',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='事件信息id')),
                ('time', models.CharField(max_length=32, verbose_name='时间')),
                ('place', models.CharField(max_length=32, verbose_name='地点')),
                ('trigger', models.CharField(max_length=32, verbose_name='触发器')),
                ('people', models.CharField(max_length=32, verbose_name='人物')),
                ('things', models.CharField(max_length=32, verbose_name='事情')),
                ('moves', models.CharField(max_length=32, verbose_name='动作')),
                ('events', models.CharField(max_length=32, verbose_name='事件')),
                ('institution', models.CharField(max_length=32, verbose_name='机构')),
                ('numbers', models.CharField(max_length=32, verbose_name='数量')),
                ('unit', models.CharField(max_length=32, verbose_name='单元')),
                ('reason', models.CharField(max_length=32, verbose_name='原因')),
                ('event_id', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, to='app.event')),
            ],
        ),
    ]
