# Generated by Django 4.1.3 on 2023-03-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_event_statistics_event_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key_words',
            name='numbers',
            field=models.IntegerField(verbose_name='重复次数'),
        ),
    ]
