# Generated by Django 4.1.3 on 2023-03-04 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_event_statistics_attitude_statistics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='key_words',
        ),
    ]
