# Generated by Django 4.1.3 on 2023-03-04 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_key_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_information',
            name='event_id',
            field=models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, to='app.event_statistics'),
        ),
        migrations.CreateModel(
            name='event_key_words',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='关键词id')),
                ('time', models.DateTimeField(verbose_name='事件时间')),
                ('word', models.CharField(max_length=32, verbose_name='关键词')),
                ('numbers', models.IntegerField(verbose_name='重复次数')),
                ('event_id', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, to='app.event_statistics')),
            ],
        ),
        migrations.CreateModel(
            name='comments_key_words',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='关键词id')),
                ('time', models.DateTimeField(verbose_name='事件时间')),
                ('word', models.CharField(max_length=32, verbose_name='关键词')),
                ('numbers', models.IntegerField(verbose_name='重复次数')),
                ('attitude', models.SmallIntegerField(choices=[(0, '高兴'), (1, '搞笑'), (2, '期待'), (3, '肯定'), (4, '感动'), (5, '悲伤'), (6, '愤怒'), (7, '厌恶'), (8, '担心'), (9, '无聊'), (10, '警惕'), (11, '惊讶'), (12, '无所谓')], verbose_name='心态')),
                ('event_id', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, to='app.event_statistics')),
            ],
        ),
    ]
