# Generated by Django 4.1.3 on 2023-03-04 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_event_information_event_id_event_key_words_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='attitude_statistics',
        ),
    ]
