# Generated by Django 4.1.3 on 2023-03-04 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_delete_attitude_statistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments_statistics',
            fields=[
                ('comments_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='心态统计id')),
                ('comment_time', models.DateTimeField(verbose_name='心态时间')),
                ('content', models.CharField(max_length=255, verbose_name='内容')),
                ('province', models.SmallIntegerField(choices=[(0, '北京'), (1, '天津'), (2, '上海'), (3, '重庆'), (4, '河北'), (5, '山西'), (6, '辽宁'), (7, '吉林'), (8, '黑龙江'), (9, '江苏'), (10, '浙江'), (11, '安徽'), (12, '福建'), (13, '江西'), (14, '山东'), (15, '河南'), (16, '湖北'), (17, '湖南'), (18, '广东'), (19, '海南'), (20, '四川'), (21, '贵州'), (22, '云南'), (23, '陕西'), (24, '甘肃'), (25, '青海'), (26, '台湾'), (27, '内蒙古'), (28, '广西'), (29, '西藏'), (30, '宁夏'), (31, '新疆'), (32, '香港'), (33, '澳门'), (34, '其他')], verbose_name='省份')),
                ('attitude', models.SmallIntegerField(choices=[(0, '高兴'), (1, '搞笑'), (2, '期待'), (3, '肯定'), (4, '感动'), (5, '悲伤'), (6, '愤怒'), (7, '厌恶'), (8, '担心'), (9, '无聊'), (10, '警惕'), (11, '惊讶'), (12, '无所谓')], verbose_name='心态')),
                ('thumbs', models.IntegerField(verbose_name='点赞数')),
                ('event_id', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, to='app.event_statistics')),
            ],
        ),
        migrations.AlterField(
            model_name='train',
            name='comments_id',
            field=models.ForeignKey(db_column='comments_id', on_delete=django.db.models.deletion.CASCADE, to='app.comments_statistics'),
        ),
        migrations.AlterField(
            model_name='untrain',
            name='comments_id',
            field=models.ForeignKey(db_column='comments_id', on_delete=django.db.models.deletion.CASCADE, to='app.comments_statistics'),
        ),
    ]
