# Generated by Django 4.1.3 on 2023-03-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_comments_statistics_alter_train_comments_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments_statistics',
            name='comments_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='心态统计id'),
        ),
    ]
