# Generated by Django 4.1.3 on 2023-03-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_comments_statistics_comments_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_statistics',
            name='attitude',
            field=models.SmallIntegerField(choices=[(0, '高兴'), (1, '搞笑'), (2, '期待'), (3, '肯定'), (4, '感动'), (5, '悲伤'), (6, '愤怒'), (7, '厌恶'), (8, '担心'), (9, '无聊'), (10, '警惕'), (11, '惊讶'), (12, '无所谓')], default=1, verbose_name='心态'),
            preserve_default=False,
        ),
    ]
