# Generated by Django 4.1.3 on 2023-03-05 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_event_statistics_attitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='event_distribution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='事件信息id')),
                ('event_time', models.DateTimeField(verbose_name='事件时间')),
                ('province', models.SmallIntegerField(choices=[(0, '北京'), (1, '天津'), (2, '上海'), (3, '重庆'), (4, '河北'), (5, '山西'), (6, '辽宁'), (7, '吉林'), (8, '黑龙江'), (9, '江苏'), (10, '浙江'), (11, '安徽'), (12, '福建'), (13, '江西'), (14, '山东'), (15, '河南'), (16, '湖北'), (17, '湖南'), (18, '广东'), (19, '海南'), (20, '四川'), (21, '贵州'), (22, '云南'), (23, '陕西'), (24, '甘肃'), (25, '青海'), (26, '台湾'), (27, '内蒙古'), (28, '广西'), (29, '西藏'), (30, '宁夏'), (31, '新疆'), (32, '香港'), (33, '澳门'), (34, '其他')], verbose_name='省份')),
                ('attitude', models.SmallIntegerField(choices=[(0, '高兴'), (1, '搞笑'), (2, '期待'), (3, '肯定'), (4, '感动'), (5, '悲伤'), (6, '愤怒'), (7, '厌恶'), (8, '担心'), (9, '无聊'), (10, '警惕'), (11, '惊讶'), (12, '无所谓')], verbose_name='心态')),
                ('hot', models.IntegerField(verbose_name='热度')),
            ],
        ),
        migrations.RenameField(
            model_name='event_statistics',
            old_name='attitude',
            new_name='total_attitudes',
        ),
        migrations.RemoveField(
            model_name='event_statistics',
            name='event_time',
        ),
        migrations.RemoveField(
            model_name='event_statistics',
            name='hot',
        ),
        migrations.RemoveField(
            model_name='event_statistics',
            name='province',
        ),
        migrations.AddField(
            model_name='event_statistics',
            name='events',
            field=models.CharField(default=1, max_length=32, verbose_name='事件'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event_statistics',
            name='institution',
            field=models.CharField(default=1, max_length=32, verbose_name='机构'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event_statistics',
            name='moves',
            field=models.CharField(default=1, max_length=32, verbose_name='动作'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event_statistics',
            name='numbers',
            field=models.CharField(default=1, max_length=32, verbose_name='数量'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event_statistics',
            name='people',
            field=models.CharField(default=1, max_length=32, verbose_name='人物'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event_statistics',
            name='place',
            field=models.CharField(default=1, max_length=32, verbose_name='地点'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event_statistics',
            name='reason',
            field=models.CharField(default=1, max_length=32, verbose_name='原因'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event_statistics',
            name='things',
            field=models.CharField(default=1, max_length=32, verbose_name='事情'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event_statistics',
            name='time',
            field=models.CharField(default=1, max_length=32, verbose_name='时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event_statistics',
            name='trigger',
            field=models.CharField(default=1, max_length=32, verbose_name='触发器'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event_statistics',
            name='unit',
            field=models.CharField(default=1, max_length=32, verbose_name='单元'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='event_information',
        ),
        migrations.AddField(
            model_name='event_distribution',
            name='event_id',
            field=models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, to='app.event_statistics'),
        ),
    ]
