# Generated by Django 4.1.3 on 2023-03-05 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_event_distribution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_distribution',
            name='attitude',
        ),
    ]
