# Generated by Django 4.1.3 on 2023-03-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_event_distribution_attitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_statistics',
            name='events',
            field=models.CharField(blank=True, max_length=32, verbose_name='事件'),
        ),
        migrations.AlterField(
            model_name='event_statistics',
            name='institution',
            field=models.CharField(blank=True, max_length=32, verbose_name='机构'),
        ),
        migrations.AlterField(
            model_name='event_statistics',
            name='moves',
            field=models.CharField(blank=True, max_length=32, verbose_name='动作'),
        ),
        migrations.AlterField(
            model_name='event_statistics',
            name='numbers',
            field=models.CharField(blank=True, max_length=32, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='event_statistics',
            name='people',
            field=models.CharField(blank=True, max_length=32, verbose_name='人物'),
        ),
        migrations.AlterField(
            model_name='event_statistics',
            name='place',
            field=models.CharField(blank=True, max_length=32, verbose_name='地点'),
        ),
        migrations.AlterField(
            model_name='event_statistics',
            name='reason',
            field=models.CharField(blank=True, max_length=32, verbose_name='原因'),
        ),
        migrations.AlterField(
            model_name='event_statistics',
            name='things',
            field=models.CharField(blank=True, max_length=32, verbose_name='事情'),
        ),
        migrations.AlterField(
            model_name='event_statistics',
            name='time',
            field=models.CharField(blank=True, max_length=32, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='event_statistics',
            name='trigger',
            field=models.CharField(blank=True, max_length=32, verbose_name='触发器'),
        ),
        migrations.AlterField(
            model_name='event_statistics',
            name='unit',
            field=models.CharField(blank=True, max_length=32, verbose_name='单元'),
        ),
    ]
