# Generated by Django 4.1.3 on 2023-03-06 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_event_statistics_events_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_key_words',
            name='event_id',
        ),
    ]
