# Generated by Django 4.1.3 on 2023-03-12 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_event_key_words_event_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='crawler_information',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='爬虫信息id')),
                ('time', models.DateTimeField(verbose_name='爬虫时间')),
                ('add', models.IntegerField(verbose_name='新增爬虫数量')),
                ('positive', models.IntegerField(verbose_name='积极')),
                ('neutral', models.IntegerField(verbose_name='中性')),
                ('negative', models.IntegerField(verbose_name='消极')),
            ],
        ),
        migrations.AddField(
            model_name='train',
            name='correct',
            field=models.BooleanField(default=1, verbose_name='更正标签'),
            preserve_default=False,
        ),
    ]
