# Generated by Django 4.1.3 on 2023-03-22 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_crawler_information_train_correct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='train',
        ),
    ]
