# Generated by Django 4.1.3 on 2023-03-22 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_delete_train'),
    ]

    operations = [
        migrations.CreateModel(
            name='train',
            fields=[
                ('train_id', models.AutoField(primary_key=True, serialize=False, verbose_name='训练id')),
                ('label', models.SmallIntegerField(choices=[(0, '高兴'), (1, '搞笑'), (2, '期待'), (3, '肯定'), (4, '感动'), (5, '悲伤'), (6, '愤怒'), (7, '厌恶'), (8, '担心'), (9, '无聊'), (10, '警惕'), (11, '惊讶'), (12, '无所谓')], verbose_name='心态标签')),
                ('correct', models.BooleanField(verbose_name='更正标签')),
                ('time', models.DateTimeField(verbose_name='手动更正时间')),
                ('comments_id', models.ForeignKey(db_column='comments_id', on_delete=django.db.models.deletion.CASCADE, to='app.comments_statistics')),
            ],
        ),
    ]
